### ISSUE TITLE
Asset paths not using the correct URL

### ISSUE THREAD

**Issue by matthewhilton** [catalyst/moodle-mod_hvp#30]
Regression of #29 

On most sites using the standard `https://example.com` URL form the updated plugin works perfectly fine, but on unit testing it sets $CFG->wwwroot to `https://example.com/moodle` which means the mod_hvp plugin tries to load the JS files from the wrong route - it tries to load for e.g. `/moodle/mod/hvp/library/js/jquery.js` instead of the actual `/mod/hvp/library/js/jquery.js`

This is probably because of the following lines:

https://github.com/catalyst/moodle-mod_hvp/blob/15cd498e2d27e9b45c63ee9a0887e2dffe713ffb/locallib.php#L110-L111

It appears the regex is trying to drop the prefix + domain part of the $CFG->wwwroot value, which is not working if the moodle is not on the root path of the url

The fix for this *should* be to just reference `/mod/hvp/library` since AFAIK moodle will automatically append this to the actual WWW root.

**Comment by jaypha** [comment]
It looks like $liburl isn't used anymore, so it can be stripped out and $relpath set directly.
These are the lines affected.

https://github.com/catalyst/moodle-mod_hvp/blob/15cd498e2d27e9b45c63ee9a0887e2dffe713ffb/library_list.php#L117
https://github.com/catalyst/moodle-mod_hvp/blob/15cd498e2d27e9b45c63ee9a0887e2dffe713ffb/locallib.php#L110
https://github.com/catalyst/moodle-mod_hvp/blob/15cd498e2d27e9b45c63ee9a0887e2dffe713ffb/upgrade_content_page.php#L97
